---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: 868d75e0-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: 868d75e1-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: 868d75e2-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: 868d9cf0-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: 868d9cf1-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: 868dc400-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: 868dc401-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: 868dc402-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: 868dc403-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: 868dc404-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: 868dc405-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: 868dc406-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: 868dc407-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: 868dc408-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: 868dc409-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: 868dc40a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: 868dc40b-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Navigate & manipulate the file system via the command line
    SuccessCriteria:
      - Traverse the file system using both relative and absolute paths
      - 'Create, move, rename, and delete files and directories'
      - Use the wildcard character to perform complex operations
      - Read files from the command line
      - Combine multiple commands
      - Redirect content from one file or command to another
      - Open and exit Vim
    ContentFiles:
      - Type: Lesson
        UID: 868dc40c-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: 868dc40d-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: 868dc40e-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: 868dc40f-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: 868dc410-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: 868dc411-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: 868dc412-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: 868dc413-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: 868dc414-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: 868dc415-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: 868dc416-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /command-line/99-checkpoint.md
        Autoscore: false
  - Title: Git
    UID: 868dc417-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Utilize Git for version control
    SuccessCriteria:
      - Initialize and delete local git repositories
      - 'Stage, commit, and see the diff of files'
      - Log git history
      - Make new branches and develop work on those branches
      - Follow a feature/branch workflow
      - Solve merge conflicts
      - Synchronize a local git repository and a GitHub repository
      - 'Add, remove, and modify remotes'
      - Fork and clone a repository you do not own
      - Pull new additions from a forked repository
    ContentFiles:
      - Type: Lesson
        UID: 868dc418-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/00-overview.md
      - Type: Lesson
        UID: 868dc419-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/01-git-concepts.md
      - Type: Lesson
        UID: 868dc41a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/02-submitting-assignments.md
      - Type: Lesson
        UID: 868deb10-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/03-exercise.md
      - Type: Lesson
        UID: 868deb11-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/04-init-remove.md
      - Type: Lesson
        UID: 868deb12-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/05-stage-commit-diff.md
      - Type: Lesson
        UID: 868deb13-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/06-log.md
      - Type: Lesson
        UID: 868deb14-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/07-branches.md
      - Type: Lesson
        UID: 868deb15-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/08-feature-branch.md
      - Type: Lesson
        UID: 868deb16-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/09-merge.md
      - Type: Lesson
        UID: 868deb17-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/10-exercise.md
      - Type: Lesson
        UID: 868deb18-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/11-sync.md
      - Type: Lesson
        UID: 868deb19-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/12-remotes.md
      - Type: Lesson
        UID: 868deb1a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/13-forking.md
      - Type: Lesson
        UID: 868deb1b-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/14-pulling-new-changes.md
      - Type: Checkpoint
        UID: 868deb1c-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /git/99-checkpoint.md
        Autoscore: false
  - Title: Javascript Fundamentals
    UID: 868deb1d-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Utilize Javascript to solve accumulator problems
    SuccessCriteria:
      - 'Declare new, well-named variables with `var` and assign values to them'
      - Use arithmetic operators on numbers
      - Compare numbers and booleans
      - Coerce strings into numbers with `==`
      - Use template literals to use stored values in a string
      - Create arrays with and without elements using the array literal syntax
      - Access and replace values with bracket notation
      - Add and remove from arrays with native array methods
      - Create objects with and without contents using the object literal syntax
      - >-
        Access, replace, and add new values with bracket notation and dot
        notation
      - 'Create, access, and manipulate arrays/objects inside of arrays/objects'
      - Loop a certain number of times with `for` and `while`
      - Loop over arrays and objects
      - Use conditionals to branch code
      - >-
        Use switch statements to handle multiple possible values to control the
        flow of programs
      - >-
        Use objects to handle multiple possible values to control the flow of
        programs
      - Loop through deeply nested arrays and objects with for loops
      - Use the browser's console to identify client-side JavaScript errors
      - Identify common error types and their meanings
      - Solve a bug with \"wolf fencing\"
      - >-
        Use Chrome breakpoints to stop the execution of code to identify and
        solve problems
      - >-
        Use the node debugger to step through code to identify and solve
        problems
      - Identify the parts of the accumulator pattern
      - >-
        Write join, leftPad, rightPad, sum, and average functions using the
        accumulator pattern
      - 'Write min, max, and indexOf using the accumulator pattern'
    ContentFiles:
      - Type: Lesson
        UID: 868deb1e-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/00-overview.md
      - Type: Lesson
        UID: 868e6040-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/01-vars.md
      - Type: Lesson
        UID: 868e6041-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/02-arithmetic-operators.md
      - Type: Lesson
        UID: 868e6042-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/03-compare-numbers-and-booleans.md
      - Type: Lesson
        UID: 868e6043-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/04-coercion.md
      - Type: Lesson
        UID: 868e6044-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/05-templates.md
      - Type: Lesson
        UID: 868e6045-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/06-exercise.md
      - Type: Lesson
        UID: 868e6046-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/07-create-arrays.md
      - Type: Lesson
        UID: 868e8750-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/08-access-arrays.md
      - Type: Lesson
        UID: 868e8751-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/09-native-array-methods.md
      - Type: Lesson
        UID: 868e8752-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/10-create-objects.md
      - Type: Lesson
        UID: 868e8753-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/11-access-objects.md
      - Type: Lesson
        UID: 868e8754-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/12-nested-structures.md
      - Type: Lesson
        UID: 868e8755-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/13-exercise.md
      - Type: Lesson
        UID: 868e8756-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/14-for-and-while.md
      - Type: Lesson
        UID: 868e8757-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/15-arrays-and-objects.md
      - Type: Lesson
        UID: 868e8758-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/16-conditionals.md
      - Type: Lesson
        UID: 868e8759-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/17-switch.md
      - Type: Lesson
        UID: 868e875a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/18-nested.md
      - Type: Lesson
        UID: 868e875b-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/19-exercise.md
      - Type: Lesson
        UID: 868e875c-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/20-expressions.md
      - Type: Lesson
        UID: 868e875d-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/21-declarations.md
      - Type: Lesson
        UID: 868e875e-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/22-return-values.md
      - Type: Lesson
        UID: 868e875f-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/23-side-effects.md
      - Type: Lesson
        UID: 868e8760-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/24-multiple-params.md
      - Type: Lesson
        UID: 868e8761-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/25-calls-within-calls.md
      - Type: Lesson
        UID: 868e8762-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/26-exercise.md
      - Type: Lesson
        UID: 868e8763-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/27-accumulator-parts.md
      - Type: Lesson
        UID: 868e8764-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/28-accumulator-uses.md
      - Type: Lesson
        UID: 868e8765-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/29-more-accumulator-uses.md
      - Type: Checkpoint
        UID: 868e8766-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /js-fundamentals/99-checkpoint.md
        Autoscore: false
  - Title: HTML
    UID: 868e8767-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Write valid and semantic HTML to form the basic structure of a webpage
    SuccessCriteria:
      - HTML is properly indented
      - >-
        HTML contains a head and a body, tags are properly closed except for
        single tag elements, and is overall valid
      - HTML relies on semantic tags
      - >-
        HTML attributes and values are used to create images, links, unique ids,
        and inline style
      - 'Forms are valid and includes labels with inputs, ids, and names'
      - Checkboxes and radio buttons are grouped and labeled
    ContentFiles:
      - Type: Lesson
        UID: 868e8768-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/00-overview.md
      - Type: Lesson
        UID: 868e8769-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/01-indentation.md
      - Type: Lesson
        UID: 868e876a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/subtrees/README.md
      - Type: Lesson
        UID: 868e876b-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/subtrees/Semantic.md
      - Type: Lesson
        UID: 868e876c-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/04-attributes.md
      - Type: Lesson
        UID: 868e876d-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/05-form-basics.md
      - Type: Lesson
        UID: 868e876e-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /html/subtrees/Forms.md
      - Type: Checkpoint
        Path: /html/99-checkpoint.md
        UID: 868e876f-b3cf-11e8-a5cc-abb59c2f76b4
        Autoscore: false
  - Title: CSS
    UID: 868e8770-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Add style and form to webpages with CSS
    SuccessCriteria:
      - >-
        Include a `<style>` element in the `<head>` of your HTML document or a
        `<link>` element with reference to a stylesheet
      - Uses inspector tool to debug problems and test CSS
      - 'Style elements, classes, pseudo-elements, and pseudo-classes'
      - >-
        Split CSS into multiple pages and wholly exclude inline styles, id
        selectors, and !important
    ContentFiles:
      - Type: Lesson
        UID: 868e8771-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/00-overview.md
      - Type: Lesson
        UID: 868e8772-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/subtrees/README.md
      - Type: Lesson
        UID: 868e8773-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/02-inspector.md
      - Type: Lesson
        UID: 868e8774-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/03-styling.md
      - Type: Lesson
        UID: 868e8775-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/04-segment-files.md
      - Type: Lesson
        UID: 868e8776-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/05-exercise.md
      - Type: Lesson
        UID: 868e8777-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /css/06-display.md
      - Type: Checkpoint
        Path: /css/99-checkpoint.md
        UID: 868e8778-b3cf-11e8-a5cc-abb59c2f76b4
        Autoscore: false
  - Title: UI Frameworks
    UID: 868e8779-b3cf-11e8-a5cc-abb59c2f76b4
    Description: Add style and form to webpages with CSS
    SuccessCriteria:
      - >-
        Rows are appropriately used with columns / smaller units and can be
        nested inside one another
    ContentFiles:
      - Type: Lesson
        UID: 868e877a-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /ui-frameworks/00-overview.md
      - Type: Lesson
        UID: 868e877b-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /ui-frameworks/01-css-frameworks.md
      - Type: Lesson
        UID: 868e877c-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /ui-frameworks/02-bootstrap-intro.md
      - Type: Lesson
        UID: 868e877d-b3cf-11e8-a5cc-abb59c2f76b4
        Path: /ui-frameworks/03-bootstrap-grand.md
      - Type: Checkpoint
        Path: /ui-frameworks/99-checkpoint.md
        UID: 868e877e-b3cf-11e8-a5cc-abb59c2f76b4
        Autoscore: false
