---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: 06a69920-b3c9-11e8-927b-df29d2850fda
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: 06a69921-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: 06a69922-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: 06a69923-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: 06a6c030-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: 06a6c031-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: 06a6c032-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: 06a6c033-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: 06a6c034-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: 06a6c035-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: 06a6c036-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: 06a6c037-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: 06a6c038-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: 06a6c039-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: 06a6c03a-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: 06a6c03b-b3c9-11e8-927b-df29d2850fda
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: 06a6c03c-b3c9-11e8-927b-df29d2850fda
    Description: Navigate & manipulate the file system via the command line
    SuccessCriteria:
      - Traverse the file system using both relative and absolute paths
      - 'Create, move, rename, and delete files and directories'
      - Use the wildcard character to perform complex operations
      - Read files from the command line
      - Combine multiple commands
      - Redirect content from one file or command to another
      - Open and exit Vim
    ContentFiles:
      - Type: Lesson
        UID: 06a6c03d-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: 06a6c03e-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: 06a6c03f-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: 06a6c040-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: 06a6c041-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: 06a6c042-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: 06a6c043-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: 06a6c044-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: 06a6c045-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: 06a6c046-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: 06a6c047-b3c9-11e8-927b-df29d2850fda
        Path: /command-line/99-checkpoint.md
        Autoscore: false
  - Title: Git
    UID: 06a6c048-b3c9-11e8-927b-df29d2850fda
    Description: Utilize Git for version control
    SuccessCriteria:
      - Initialize and delete local git repositories
      - 'Stage, commit, and see the diff of files'
      - Log git history
      - Make new branches and develop work on those branches
      - Follow a feature/branch workflow
      - Solve merge conflicts
      - Synchronize a local git repository and a GitHub repository
      - 'Add, remove, and modify remotes'
      - Fork and clone a repository you do not own
      - Pull new additions from a forked repository
    ContentFiles:
      - Type: Lesson
        UID: 06a6c049-b3c9-11e8-927b-df29d2850fda
        Path: /git/00-overview.md
      - Type: Lesson
        UID: 06a6c04a-b3c9-11e8-927b-df29d2850fda
        Path: /git/01-git-concepts.md
      - Type: Lesson
        UID: 06a6c04b-b3c9-11e8-927b-df29d2850fda
        Path: /git/02-submitting-assignments.md
      - Type: Lesson
        UID: 06a6c04c-b3c9-11e8-927b-df29d2850fda
        Path: /git/03-exercise.md
      - Type: Lesson
        UID: 06a6c04d-b3c9-11e8-927b-df29d2850fda
        Path: /git/04-init-remove.md
      - Type: Lesson
        UID: 06a6c04e-b3c9-11e8-927b-df29d2850fda
        Path: /git/05-stage-commit-diff.md
      - Type: Lesson
        UID: 06a6c04f-b3c9-11e8-927b-df29d2850fda
        Path: /git/06-log.md
      - Type: Lesson
        UID: 06a6c050-b3c9-11e8-927b-df29d2850fda
        Path: /git/07-branches.md
      - Type: Lesson
        UID: 06a6c051-b3c9-11e8-927b-df29d2850fda
        Path: /git/08-feature-branch.md
      - Type: Lesson
        UID: 06a6c052-b3c9-11e8-927b-df29d2850fda
        Path: /git/09-merge.md
      - Type: Lesson
        UID: 06a6c053-b3c9-11e8-927b-df29d2850fda
        Path: /git/10-exercise.md
      - Type: Lesson
        UID: 06a6c054-b3c9-11e8-927b-df29d2850fda
        Path: /git/11-sync.md
      - Type: Lesson
        UID: 06a6c055-b3c9-11e8-927b-df29d2850fda
        Path: /git/12-remotes.md
      - Type: Lesson
        UID: 06a6c056-b3c9-11e8-927b-df29d2850fda
        Path: /git/13-forking.md
      - Type: Lesson
        UID: 06a6c057-b3c9-11e8-927b-df29d2850fda
        Path: /git/14-pulling-new-changes.md
      - Type: Checkpoint
        UID: 06a6c058-b3c9-11e8-927b-df29d2850fda
        Path: /git/99-checkpoint.md
        Autoscore: false
  - Title: Javascript Fundamentals
    UID: 06a6e740-b3c9-11e8-927b-df29d2850fda
    Description: Utilize Javascript to solve accumulator problems
    SuccessCriteria:
      - 'Declare new, well-named variables with `var` and assign values to them'
      - Use arithmetic operators on numbers
      - Compare numbers and booleans
      - Coerce strings into numbers with `==`
      - Use template literals to use stored values in a string
      - Create arrays with and without elements using the array literal syntax
      - Access and replace values with bracket notation
      - Add and remove from arrays with native array methods
      - Create objects with and without contents using the object literal syntax
      - >-
        Access, replace, and add new values with bracket notation and dot
        notation
      - 'Create, access, and manipulate arrays/objects inside of arrays/objects'
      - Loop a certain number of times with `for` and `while`
      - Loop over arrays and objects
      - Use conditionals to branch code
      - >-
        Use switch statements to handle multiple possible values to control the
        flow of programs
      - >-
        Use objects to handle multiple possible values to control the flow of
        programs
      - Loop through deeply nested arrays and objects with for loops
      - Use the browser's console to identify client-side JavaScript errors
      - Identify common error types and their meanings
      - Solve a bug with \"wolf fencing\"
      - >-
        Use Chrome breakpoints to stop the execution of code to identify and
        solve problems
      - >-
        Use the node debugger to step through code to identify and solve
        problems
      - Identify the parts of the accumulator pattern
      - >-
        Write join, leftPad, rightPad, sum, and average functions using the
        accumulator pattern
      - 'Write min, max, and indexOf using the accumulator pattern'
    ContentFiles:
      - Type: Lesson
        UID: 06a6e741-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/00-overview.md
      - Type: Lesson
        UID: 06a75c70-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/01-vars.md
      - Type: Lesson
        UID: 06a78380-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/02-arithmetic-operators.md
      - Type: Lesson
        UID: 06a78381-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/03-compare-numbers-and-booleans.md
      - Type: Lesson
        UID: 06a78382-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/04-coercion.md
      - Type: Lesson
        UID: 06a78383-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/05-templates.md
      - Type: Lesson
        UID: 06a78384-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/06-exercise.md
      - Type: Lesson
        UID: 06a78385-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/07-create-arrays.md
      - Type: Lesson
        UID: 06a78386-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/08-access-arrays.md
      - Type: Lesson
        UID: 06a78387-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/09-native-array-methods.md
      - Type: Lesson
        UID: 06a78388-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/10-create-objects.md
      - Type: Lesson
        UID: 06a78389-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/11-access-objects.md
      - Type: Lesson
        UID: 06a7838a-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/12-nested-structures.md
      - Type: Lesson
        UID: 06a7838b-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/13-exercise.md
      - Type: Lesson
        UID: 06a7838c-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/14-for-and-while.md
      - Type: Lesson
        UID: 06a7838d-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/15-arrays-and-objects.md
      - Type: Lesson
        UID: 06a7838e-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/16-conditionals.md
      - Type: Lesson
        UID: 06a7838f-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/17-switch.md
      - Type: Lesson
        UID: 06a78390-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/18-nested.md
      - Type: Lesson
        UID: 06a78391-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/19-exercise.md
      - Type: Lesson
        UID: 06a78392-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/20-expressions.md
      - Type: Lesson
        UID: 06a78393-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/21-declarations.md
      - Type: Lesson
        UID: 06a78394-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/22-return-values.md
      - Type: Lesson
        UID: 06a78395-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/23-side-effects.md
      - Type: Lesson
        UID: 06a78396-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/24-multiple-params.md
      - Type: Lesson
        UID: 06a78397-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/25-calls-within-calls.md
      - Type: Lesson
        UID: 06a7aa90-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/26-exercise.md
      - Type: Lesson
        UID: 06a7aa91-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/27-accumulator-parts.md
      - Type: Lesson
        UID: 06a7aa92-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/28-accumulator-uses.md
      - Type: Lesson
        UID: 06a7aa93-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/29-more-accumulator-uses.md
      - Type: Checkpoint
        UID: 06a7aa94-b3c9-11e8-927b-df29d2850fda
        Path: /js-fundamentals/99-checkpoint.md
        Autoscore: false
  - Title: HTML
    UID: 06a7aa95-b3c9-11e8-927b-df29d2850fda
    Description: Write valid and semantic HTML to form the basic structure of a webpage
    SuccessCriteria:
      - HTML is properly indented
      - >-
        HTML contains a head and a body, tags are properly closed except for
        single tag elements, and is overall valid
      - HTML relies on semantic tags
      - >-
        HTML attributes and values are used to create images, links, unique ids,
        and inline style
      - 'Forms are valid and includes labels with inputs, ids, and names'
      - Checkboxes and radio buttons are grouped and labeled
    ContentFiles:
      - Type: Lesson
        UID: 06a7aa96-b3c9-11e8-927b-df29d2850fda
        Path: /html/00-overview.md
      - Type: Lesson
        UID: 06a7aa97-b3c9-11e8-927b-df29d2850fda
        Path: /html/01-indentation.md
      - Type: Lesson
        UID: 06a7aa98-b3c9-11e8-927b-df29d2850fda
        Path: /html/subtrees/README.md
      - Type: Lesson
        UID: 06a7aa99-b3c9-11e8-927b-df29d2850fda
        Path: /html/subtrees/Semantic.md
      - Type: Lesson
        UID: 06a7aa9a-b3c9-11e8-927b-df29d2850fda
        Path: /html/04-attributes.md
      - Type: Lesson
        UID: 06a7aa9b-b3c9-11e8-927b-df29d2850fda
        Path: /html/05-form-basics.md
      - Type: Lesson
        UID: 06a7aa9c-b3c9-11e8-927b-df29d2850fda
        Path: /html/subtrees/Forms.md
      - Type: Checkpoint
        Path: /html/99-checkpoint.md
        UID: 06a7aa9d-b3c9-11e8-927b-df29d2850fda
        Autoscore: false
  - Title: CSS
    UID: 06a7aa9e-b3c9-11e8-927b-df29d2850fda
    Description: Add style and form to webpages with CSS
    SuccessCriteria:
      - >-
        Include a `<style>` element in the `<head>` of your HTML document or a
        `<link>` element with reference to a stylesheet
      - Uses inspector tool to debug problems and test CSS
      - 'Style elements, classes, pseudo-elements, and pseudo-classes'
      - >-
        Split CSS into multiple pages and wholly exclude inline styles, id
        selectors, and !important
    ContentFiles:
      - Type: Lesson
        UID: 06a7aa9f-b3c9-11e8-927b-df29d2850fda
        Path: /css/00-overview.md
      - Type: Lesson
        UID: 06a7aaa0-b3c9-11e8-927b-df29d2850fda
        Path: /css/subtrees/README.md
      - Type: Lesson
        UID: 06a7aaa1-b3c9-11e8-927b-df29d2850fda
        Path: /css/02-inspector.md
      - Type: Lesson
        UID: 06a7aaa2-b3c9-11e8-927b-df29d2850fda
        Path: /css/03-styling.md
      - Type: Lesson
        UID: 06a7aaa3-b3c9-11e8-927b-df29d2850fda
        Path: /css/04-segment-files.md
      - Type: Lesson
        UID: 06a7aaa4-b3c9-11e8-927b-df29d2850fda
        Path: /css/05-exercise.md
      - Type: Lesson
        UID: 06a7aaa5-b3c9-11e8-927b-df29d2850fda
        Path: /css/06-display.md
      - Type: Checkpoint
        Path: /css/99-checkpoint.md
        UID: 06a7aaa6-b3c9-11e8-927b-df29d2850fda
        Autoscore: false
