---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: e385e8a0-b3b0-11e8-8746-5f37e6db2a75
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: e3860fb0-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: e3860fb1-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: e3860fb2-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: e3860fb3-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: e3860fb4-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: e3860fb5-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: e38636c0-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: e38636c1-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: e38636c2-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: e38636c3-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: e38636c4-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: e38636c5-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: e38636c6-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: e38636c7-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: e38636c8-b3b0-11e8-8746-5f37e6db2a75
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: e38636c9-b3b0-11e8-8746-5f37e6db2a75
    Description: placeholder
    SuccessCriteria:
      - placeholder
    ContentFiles:
      - Type: Lesson
        UID: e38636ca-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: e38636cb-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: e38636cc-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: e38636cd-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: e38636ce-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: e38636cf-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: e3865dd0-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: e3865dd1-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: e3865dd2-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: e3865dd3-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: e3865dd4-b3b0-11e8-8746-5f37e6db2a75
        Path: /command-line/99-checkpoint.md
        Autoscore: false
