---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: ba78d9c0-b3a8-11e8-85c6-85b9be4b4a33
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: ba7900d0-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: ba7900d1-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: ba7927e0-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: ba7927e1-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: ba7927e2-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: ba794ef0-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: ba794ef1-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: ba794ef2-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: ba797600-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: ba797601-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: ba797602-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: ba799d10-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: ba799d11-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: ba79c420-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: ba79c421-b3a8-11e8-85c6-85b9be4b4a33
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    Description: placeholder
    SuccessCriteria:
      - placeholder
    ContentFiles:
      - Type: Lesson
        UID: ba79c422-b3a8-11e8-85c6-85b9be4b4a33
        Path: /command-line/00-overview.md
      - Type: Checkpoint
        UID: ba79c423-b3a8-11e8-85c6-85b9be4b4a33
        Path: /command-line/99-checkpoint.md
        Autoscore: false
