---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: 7aaf3bb0-b3bf-11e8-9a05-b358babb11ac
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: 7aaf3bb1-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: 7aaf3bb2-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: 7aaf3bb3-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: 7aaf3bb4-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: 7aaf62c0-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: 7aaf62c1-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: 7aaf62c2-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: 7aaf62c3-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: 7aaf62c4-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: 7aaf62c5-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: 7aaf62c6-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: 7aaf62c7-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: 7aaf62c8-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: 7aaf62c9-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: 7aaf62ca-b3bf-11e8-9a05-b358babb11ac
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: 7aaf62cb-b3bf-11e8-9a05-b358babb11ac
    Description: Navigate & manipulate the file system via the command line
    SuccessCriteria:
      - Traverse the file system using both relative and absolute paths
      - 'Create, move, rename, and delete files and directories'
      - Use the wildcard character to perform complex operations
      - Read files from the command line
      - Combine multiple commands
      - Redirect content from one file or command to another
      - Open and exit Vim
    ContentFiles:
      - Type: Lesson
        UID: 7aaf62cc-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: 7aaf62cd-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: 7aaf62ce-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: 7aaf62cf-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: 7aaf62d0-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: 7aaf62d1-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: 7aaf89d0-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: 7aaf89d1-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: 7aaf89d2-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: 7aaf89d3-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: 7aaf89d4-b3bf-11e8-9a05-b358babb11ac
        Path: /command-line/99-checkpoint.md
        Autoscore: false
  - Title: Git
    UID: 7aaf89d5-b3bf-11e8-9a05-b358babb11ac
    Description: Utilize Git for version control
    SuccessCriteria:
      - Initialize and delete local git repositories
      - 'Stage, commit, and see the diff of files'
      - Log git history
      - Make new branches and develop work on those branches
      - Follow a feature/branch workflow
      - Solve merge conflicts
      - Synchronize a local git repository and a GitHub repository
      - 'Add, remove, and modify remotes'
      - Fork and clone a repository you do not own
      - Pull new additions from a forked repository
    ContentFiles:
      - Type: Lesson
        UID: 7aaf89d6-b3bf-11e8-9a05-b358babb11ac
        Path: /git/00-overview.md
      - Type: Lesson
        UID: 7aaf89d7-b3bf-11e8-9a05-b358babb11ac
        Path: /git/01-git-concepts.md
      - Type: Lesson
        UID: 7aaf89d8-b3bf-11e8-9a05-b358babb11ac
        Path: /git/02-submitting-assignments.md
      - Type: Lesson
        UID: 7aaf89d9-b3bf-11e8-9a05-b358babb11ac
        Path: /git/03-exercise.md
      - Type: Lesson
        UID: 7aaf89da-b3bf-11e8-9a05-b358babb11ac
        Path: /git/04-init-remove.md
      - Type: Lesson
        UID: 7aaf89db-b3bf-11e8-9a05-b358babb11ac
        Path: /git/05-stage-commit-diff.md
      - Type: Lesson
        UID: 7aaf89dc-b3bf-11e8-9a05-b358babb11ac
        Path: /git/06-log.md
      - Type: Lesson
        UID: 7aaf89dd-b3bf-11e8-9a05-b358babb11ac
        Path: /git/07-branches.md
      - Type: Lesson
        UID: 7aaf89de-b3bf-11e8-9a05-b358babb11ac
        Path: /git/08-feature-branch.md
      - Type: Lesson
        UID: 7aaf89df-b3bf-11e8-9a05-b358babb11ac
        Path: /git/09-merge.md
      - Type: Lesson
        UID: 7aaf89e0-b3bf-11e8-9a05-b358babb11ac
        Path: /git/10-exercise.md
      - Type: Lesson
        UID: 7aaf89e1-b3bf-11e8-9a05-b358babb11ac
        Path: /git/11-sync.md
      - Type: Lesson
        UID: 7aaf89e2-b3bf-11e8-9a05-b358babb11ac
        Path: /git/12-remotes.md
      - Type: Lesson
        UID: 7aaf89e3-b3bf-11e8-9a05-b358babb11ac
        Path: /git/13-forking.md
      - Type: Lesson
        UID: 7aaf89e4-b3bf-11e8-9a05-b358babb11ac
        Path: /git/14-pulling-new-changes.md
      - Type: Checkpoint
        UID: 7aaf89e5-b3bf-11e8-9a05-b358babb11ac
        Path: /git/99-checkpoint.md
        Autoscore: false
  - Title: Javascript Fundamentals
    UID: 7aaf89d5-b3bf-11e8-9a05-b358babb11ac
    Description: Utilize Javascript to solve accumulator problems
    SuccessCriteria:
      - 'Declare new, well-named variables with `var` and assign values to them'
      - Use arithmetic operators on numbers
      - Compare numbers and booleans
      - Coerce strings into numbers with `==`
      - Use template literals to use stored values in a string
      - Create arrays with and without elements using the array literal syntax
      - Access and replace values with bracket notation
      - Add and remove from arrays with native array methods
      - Create objects with and without contents using the object literal syntax
      - >-
        Access, replace, and add new values with bracket notation and dot
        notation
      - 'Create, access, and manipulate arrays/objects inside of arrays/objects'
      - Loop a certain number of times with `for` and `while`
      - Loop over arrays and objects
      - Use conditionals to branch code
      - >-
        Use switch statements to handle multiple possible values to control the
        flow of programs
      - >-
        Use objects to handle multiple possible values to control the flow of
        programs
      - Loop through deeply nested arrays and objects with for loops
      - Use the browser's console to identify client-side JavaScript errors
      - Identify common error types and their meanings
      - Solve a bug with \"wolf fencing\"
      - >-
        Use Chrome breakpoints to stop the execution of code to identify and
        solve problems
      - >-
        Use the node debugger to step through code to identify and solve
        problems
      - Identify the parts of the accumulator pattern
      - >-
        Write join, leftPad, rightPad, sum, and average functions using the
        accumulator pattern
      - 'Write min, max, and indexOf using the accumulator pattern'
    ContentFiles:
      - Type: Lesson
        UID: 7aaf89d6-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/00-overview.md
      - Type: Lesson
        UID: 7aaf89d7-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/01-vars.md
      - Type: Lesson
        UID: 7aaf89d8-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/02-arithmetic-operators.md
      - Type: Lesson
        UID: 7aaf89d9-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/03-compare-numbers-and-booleans.md
      - Type: Lesson
        UID: 7aaf89da-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/04-coercion.md
      - Type: Lesson
        UID: 7aaf89db-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/05-templates.md
      - Type: Lesson
        UID: 7aaf89dc-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/06-exercise.md
      - Type: Lesson
        UID: 7aaf89dd-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/07-create-arrays.md
      - Type: Lesson
        UID: 7aaf89de-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/08-access-arrays.md
      - Type: Lesson
        UID: 7aaf89df-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/09-native-array-methods.md
      - Type: Lesson
        UID: 7aaf89e0-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/10-create-objects.md
      - Type: Lesson
        UID: 7aaf89e1-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/11-access-objects.md
      - Type: Lesson
        UID: 7aaf89e2-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/12-nested-structures.md
      - Type: Lesson
        UID: 7aaf89e3-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/13-exercise.md
      - Type: Lesson
        UID: 7aaf89e4-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/14-pulling-new-changes.md
      - Type: Checkpoint
        UID: 7aaf89e5-b3bf-11e8-9a05-b358babb11ac
        Path: /js-fundamentals/99-checkpoint.md
        Autoscore: false
