---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: c0c61270-b3bc-11e8-8400-8fa12c0e7500
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: c0c61271-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: c0c61272-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: c0c61273-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: c0c61274-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: c0c63980-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: c0c63981-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: c0c63982-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: c0c63983-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: c0c63984-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: c0c63985-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: c0c63986-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: c0c63987-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: c0c63988-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: c0c63989-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: c0c6398a-b3bc-11e8-8400-8fa12c0e7500
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: c0c6398b-b3bc-11e8-8400-8fa12c0e7500
    Description: Navigate & manipulate the file system via the command line
    SuccessCriteria:
      - Traverse the file system using both relative and absolute paths
      - 'Create, move, rename, and delete files and directories'
      - Use the wildcard character to perform complex operations
      - Read files from the command line
      - Combine multiple commands
      - Redirect content from one file or command to another
      - Open and exit Vim
    ContentFiles:
      - Type: Lesson
        UID: c0c66090-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: c0c66091-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: c0c66092-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: c0c66093-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: c0c66094-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: c0c66095-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: c0c66096-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: c0c66097-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: c0c66098-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: c0c66099-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: c0c6609a-b3bc-11e8-8400-8fa12c0e7500
        Path: /command-line/99-checkpoint.md
        Autoscore: false
