---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: ffcfe980-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: ffcfe981-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: ffcfe982-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: ffd01090-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: ffd01091-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: ffd01092-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: ffd01093-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: ffd01094-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: ffd01095-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: ffd01096-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: ffd01097-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: ffd01098-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: ffd01099-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: ffd0109a-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: ffd0109b-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: ffd0109c-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: ffd0109d-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Navigate & manipulate the file system via the command line
    SuccessCriteria:
      - Traverse the file system using both relative and absolute paths
      - 'Create, move, rename, and delete files and directories'
      - Use the wildcard character to perform complex operations
      - Read files from the command line
      - Combine multiple commands
      - Redirect content from one file or command to another
      - Open and exit Vim
    ContentFiles:
      - Type: Lesson
        UID: ffd0109e-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: ffd0109f-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: ffd010a0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: ffd010a1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: ffd010a2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/04-exercise.md
      - Type: Lesson
        UID: ffd010a3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/05-read.md
      - Type: Lesson
        UID: ffd010a4-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/06-combine-commands.md
      - Type: Lesson
        UID: ffd037a0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/07-redirection.md
      - Type: Lesson
        UID: ffd037a1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/08-basic-vim.md
      - Type: Lesson
        UID: ffd037a2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/09-exercise.md
      - Type: Checkpoint
        UID: ffd037a3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /command-line/99-checkpoint.md
        Autoscore: false
  - Title: Git
    UID: ffd037a4-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Utilize Git for version control
    SuccessCriteria:
      - Initialize and delete local git repositories
      - 'Stage, commit, and see the diff of files'
      - Log git history
      - Make new branches and develop work on those branches
      - Follow a feature/branch workflow
      - Solve merge conflicts
      - Synchronize a local git repository and a GitHub repository
      - 'Add, remove, and modify remotes'
      - Fork and clone a repository you do not own
      - Pull new additions from a forked repository
    ContentFiles:
      - Type: Lesson
        UID: ffd037a5-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/00-overview.md
      - Type: Lesson
        UID: ffd037a6-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/01-git-concepts.md
      - Type: Lesson
        UID: ffd037a7-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/02-submitting-assignments.md
      - Type: Lesson
        UID: ffd037a8-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/03-exercise.md
      - Type: Lesson
        UID: ffd037a9-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/04-init-remove.md
      - Type: Lesson
        UID: ffd037aa-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/05-stage-commit-diff.md
      - Type: Lesson
        UID: ffd037ab-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/06-log.md
      - Type: Lesson
        UID: ffd037ac-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/07-branches.md
      - Type: Lesson
        UID: ffd037ad-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/08-feature-branch.md
      - Type: Lesson
        UID: ffd037ae-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/09-merge.md
      - Type: Lesson
        UID: ffd037af-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/10-exercise.md
      - Type: Lesson
        UID: ffd037b0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/11-sync.md
      - Type: Lesson
        UID: ffd037b1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/12-remotes.md
      - Type: Lesson
        UID: ffd037b2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/13-forking.md
      - Type: Lesson
        UID: ffd037b3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/14-pulling-new-changes.md
      - Type: Checkpoint
        UID: ffd037b4-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /git/99-checkpoint.md
        Autoscore: false
  - Title: Javascript Fundamentals
    UID: ffd037b5-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Utilize Javascript to solve accumulator problems
    SuccessCriteria:
      - 'Declare new, well-named variables with `var` and assign values to them'
      - Use arithmetic operators on numbers
      - Compare numbers and booleans
      - Coerce strings into numbers with `==`
      - Use template literals to use stored values in a string
      - Create arrays with and without elements using the array literal syntax
      - Access and replace values with bracket notation
      - Add and remove from arrays with native array methods
      - Create objects with and without contents using the object literal syntax
      - >-
        Access, replace, and add new values with bracket notation and dot
        notation
      - 'Create, access, and manipulate arrays/objects inside of arrays/objects'
      - Loop a certain number of times with `for` and `while`
      - Loop over arrays and objects
      - Use conditionals to branch code
      - >-
        Use switch statements to handle multiple possible values to control the
        flow of programs
      - >-
        Use objects to handle multiple possible values to control the flow of
        programs
      - Loop through deeply nested arrays and objects with for loops
      - Use the browser's console to identify client-side JavaScript errors
      - Identify common error types and their meanings
      - Solve a bug with \"wolf fencing\"
      - >-
        Use Chrome breakpoints to stop the execution of code to identify and
        solve problems
      - >-
        Use the node debugger to step through code to identify and solve
        problems
      - Identify the parts of the accumulator pattern
      - >-
        Write join, leftPad, rightPad, sum, and average functions using the
        accumulator pattern
      - 'Write min, max, and indexOf using the accumulator pattern'
    ContentFiles:
      - Type: Lesson
        UID: ffd05eb0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/00-overview.md
      - Type: Lesson
        UID: ffd0d3e0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/01-vars.md
      - Type: Lesson
        UID: ffd0d3e1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/02-arithmetic-operators.md
      - Type: Lesson
        UID: ffd0d3e2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/03-compare-numbers-and-booleans.md
      - Type: Lesson
        UID: ffd0d3e3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/04-coercion.md
      - Type: Lesson
        UID: ffd0d3e4-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/05-templates.md
      - Type: Lesson
        UID: ffd0d3e5-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/06-exercise.md
      - Type: Lesson
        UID: ffd0d3e6-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/07-create-arrays.md
      - Type: Lesson
        UID: ffd0d3e7-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/08-access-arrays.md
      - Type: Lesson
        UID: ffd0d3e8-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/09-native-array-methods.md
      - Type: Lesson
        UID: ffd0d3e9-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/10-create-objects.md
      - Type: Lesson
        UID: ffd0d3ea-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/11-access-objects.md
      - Type: Lesson
        UID: ffd0d3eb-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/12-nested-structures.md
      - Type: Lesson
        UID: ffd0d3ec-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/13-exercise.md
      - Type: Lesson
        UID: ffd0d3ed-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/14-for-and-while.md
      - Type: Lesson
        UID: ffd0d3ee-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/15-arrays-and-objects.md
      - Type: Lesson
        UID: ffd0d3ef-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/16-conditionals.md
      - Type: Lesson
        UID: ffd0d3f0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/17-switch.md
      - Type: Lesson
        UID: ffd0d3f1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/18-nested.md
      - Type: Lesson
        UID: ffd0d3f2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/19-exercise.md
      - Type: Lesson
        UID: ffd0d3f3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/20-expressions.md
      - Type: Lesson
        UID: ffd0d3f4-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/21-declarations.md
      - Type: Lesson
        UID: ffd0d3f5-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/22-return-values.md
      - Type: Lesson
        UID: ffd0d3f6-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/23-side-effects.md
      - Type: Lesson
        UID: ffd0d3f7-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/24-multiple-params.md
      - Type: Lesson
        UID: ffd0d3f8-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/25-calls-within-calls.md
      - Type: Lesson
        UID: ffd0d3f9-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/26-exercise.md
      - Type: Lesson
        UID: ffd0d3fa-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/27-accumulator-parts.md
      - Type: Lesson
        UID: ffd0d3fb-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/28-accumulator-uses.md
      - Type: Lesson
        UID: ffd0d3fc-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/29-more-accumulator-uses.md
      - Type: Checkpoint
        UID: ffd0d3fd-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /js-fundamentals/99-checkpoint.md
        Autoscore: false
  - Title: HTML
    UID: ffd0d3fe-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Write valid and semantic HTML to form the basic structure of a webpage
    SuccessCriteria:
      - HTML is properly indented
      - >-
        HTML contains a head and a body, tags are properly closed except for
        single tag elements, and is overall valid
      - HTML relies on semantic tags
      - >-
        HTML attributes and values are used to create images, links, unique ids,
        and inline style
      - 'Forms are valid and includes labels with inputs, ids, and names'
      - Checkboxes and radio buttons are grouped and labeled
    ContentFiles:
      - Type: Lesson
        UID: ffd0d3ff-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/00-overview.md
      - Type: Lesson
        UID: ffd0d400-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/01-indentation.md
      - Type: Lesson
        UID: ffd0d401-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/subtrees/README.md
      - Type: Lesson
        UID: ffd0faf0-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/subtrees/Semantic.md
      - Type: Lesson
        UID: ffd0faf1-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/04-attributes.md
      - Type: Lesson
        UID: ffd0faf2-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/05-form-basics.md
      - Type: Lesson
        UID: ffd0faf3-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /html/subtrees/Forms.md
      - Type: Checkpoint
        Path: /html/99-checkpoint.md
        UID: ffd0faf4-b3d2-11e8-8fe6-7d01bbf72d0e
        Autoscore: false
  - Title: CSS
    UID: ffd0faf5-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Add style and form to webpages with CSS
    SuccessCriteria:
      - >-
        Include a `<style>` element in the `<head>` of your HTML document or a
        `<link>` element with reference to a stylesheet
      - Uses inspector tool to debug problems and test CSS
      - 'Style elements, classes, pseudo-elements, and pseudo-classes'
      - >-
        Split CSS into multiple pages and wholly exclude inline styles, id
        selectors, and !important
    ContentFiles:
      - Type: Lesson
        UID: ffd0faf6-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/00-overview.md
      - Type: Lesson
        UID: ffd0faf7-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/subtrees/README.md
      - Type: Lesson
        UID: ffd0faf8-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/02-inspector.md
      - Type: Lesson
        UID: ffd0faf9-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/03-styling.md
      - Type: Lesson
        UID: ffd0fafa-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/04-segment-files.md
      - Type: Lesson
        UID: ffd0fafb-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/05-exercise.md
      - Type: Lesson
        UID: ffd0fafc-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /css/06-display.md
      - Type: Checkpoint
        Path: /css/99-checkpoint.md
        UID: ffd0fafd-b3d2-11e8-8fe6-7d01bbf72d0e
        Autoscore: false
  - Title: UI Frameworks
    UID: ffd0fafe-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Add style and form to webpages with CSS
    SuccessCriteria:
      - >-
        Rows are appropriately used with columns / smaller units and can be
        nested inside one another
    ContentFiles:
      - Type: Lesson
        UID: ffd0faff-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /ui-frameworks/00-overview.md
      - Type: Lesson
        UID: ffd0fb00-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /ui-frameworks/01-css-frameworks.md
      - Type: Lesson
        UID: ffd0fb01-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /ui-frameworks/02-bootstrap-intro.md
      - Type: Lesson
        UID: ffd0fb02-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /ui-frameworks/03-bootstrap-grid.md
      - Type: Checkpoint
        Path: /ui-frameworks/99-checkpoint.md
        UID: ffd0fb03-b3d2-11e8-8fe6-7d01bbf72d0e
        Autoscore: false
  - Title: DOM Manipulation
    UID: ffd0fb04-b3d2-11e8-8fe6-7d01bbf72d0e
    Description: Target, create, and manipulate DOM elements & Respond to events with event listeners
    SuccessCriteria:
      - Run DOM manipulation code after the DOM has been loaded
      - 'Remove, find, modify, create, and append DOM elements'
      - Loop over collections of nodes to manipulate multiple items
      - >-
        Fire JavaScript functions using HTML event attributes and event
        listeners
      - >-
        Hijack forms to prevent the default behavior and manipulate values from
        a form using `event`
      - Conditionally perform operations with events
      - >-
        Build a `render()` function that updates the DOM based on data stored in
        memory
    ContentFiles:
      - Type: Lesson
        UID: ffd0fb05-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/00-overview.md
      - Type: Lesson
        UID: ffd0fb06-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /subtrees/browser-dom-curriculum/DOM/README.md
      - Type: Lesson
        UID: ffd0fb07-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /subtrees/browser-dom-curriculum/DOM/02-Traversal.md
      - Type: Lesson
        UID: ffd0fb08-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /subtrees/browser-dom-curriculum/DOM/03-Manipulation.md
      - Type: Lesson
        UID: ffd0fb09-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /subtrees/browser-dom-curriculum/DOM/04-Creation and Deletion.md
      - Type: Lesson
        UID: ffd0fb0a-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/02-loop.md
      - Type: Lesson
        UID: ffd0fb0b-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/03-exercise.md
      - Type: Lesson
        UID: ffd0fb0c-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /subtrees/browser-dom-curriculum/DOM/05-Events.md
      - Type: Lesson
        UID: ffd0fb0d-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/04-prevent-default.md
      - Type: Lesson
        UID: ffd0fb0e-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/05-conditional.md
      - Type: Lesson
        UID: ffd0fb0f-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/06-render.md
      - Type: Lesson
        UID: ffd0fb10-b3d2-11e8-8fe6-7d01bbf72d0e
        Path: /dom/07-exercise.md
      - Type: Checkpoint
        Path: /dom/99-checkpoint.md
        UID: ffd0fb11-b3d2-11e8-8fe6-7d01bbf72d0e
        Autoscore: false
