---
Title: Web Fundamentals
Standards:
  - Title: Development Environment
    UID: 384ffb40-b3ad-11e8-8a60-edbe17f722b0
    Description: Customize the command line for increased productivity
    SuccessCriteria:
      - Install and configure the Slack Application
      - Install and/or configure a terminal program
      - Install and/or configure a window management tool
      - Score 25wpm or higher on typing.io with JavaScript
      - Install an operating system package manager
      - Install a text editor
      - Install Node.js
      - Install Git
      - Customize command line prompt with zsh themes
      - Print environment variables to the console
      - >-
        Define new environment variables for the existing terminal session and
        for future terminal sessions
      - Run JavaScript in the browser console
      - Run JavaScript files with node and the repl
    ContentFiles:
      - Type: Lesson
        UID: 38502250-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/00-overview.md
      - Type: Lesson
        UID: 38502251-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/01-slack.md
      - Type: Lesson
        UID: 38502252-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/02-terminal.md
      - Type: Lesson
        UID: 38502253-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/03-window-management.md
      - Type: Lesson
        UID: 38502254-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/04-typing.md
      - Type: Lesson
        UID: 38502255-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/05-homebrew.md
      - Type: Lesson
        UID: 38504960-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/06-text-editor.md
      - Type: Lesson
        UID: 38504961-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/07-node.md
      - Type: Lesson
        UID: 38504962-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/08-git.md
      - Type: Lesson
        UID: 38504963-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/09-zsh.md
      - Type: Lesson
        UID: 38504964-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/10-print.md
      - Type: Lesson
        UID: 38504965-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/11-set.md
      - Type: Lesson
        UID: 38504966-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/12-browser-console.md
      - Type: Lesson
        UID: 38504967-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/13-node.md
      - Type: Checkpoint
        UID: 38504968-b3ad-11e8-8a60-edbe17f722b0
        Path: /dev-environment/99-checkpoint.md
        Autoscore: false
  - Title: Command Line
    UID: 38504969-b3ad-11e8-8a60-edbe17f722b0
    Description: placeholder
    SuccessCriteria:
      - placeholder
    ContentFiles:
      - Type: Lesson
        UID: 3850496a-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/00-overview.md
      - Type: Lesson
        UID: 3850496b-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/01-traverse.md
      - Type: Lesson
        UID: 3850496c-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/02-manipulate.md
      - Type: Lesson
        UID: 38507070-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/03-wildcard.md
      - Type: Lesson
        UID: 38507071-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/04-exercise.md
      - Type: Checkpoint
        UID: 38507072-b3ad-11e8-8a60-edbe17f722b0
        Path: /command-line/99-checkpoint.md
        Autoscore: false
